package: flatpickr
version: '1.1.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/flatpickr
load: late
requires:
    redaxo: '^5.14.0'
    php:
        version: '>=7.4, <9'
